default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: psgr_db
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: shugyo_test

#コードのバックアップ
 
#default: &default
  #adapter: sqlite3
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #timeout: 5000

#development:
  #<<: *default
  #database: db/development.sqlite3


#test:
  #<<: *default
  #database: db/test.sqlite3

#production:
  #<<: *default
  #database: db/production.sqlite3

